### ISSUE TITLE
qt5-webengine: Enable debug build of Chromium

### ISSUE THREAD

**Issue by yan12125** [qutebrowser/qt-debug-pkgbuild#19]
Chromium provides [an option](https://www.chromium.org/developers/gn-build-configuration) to build in the debug mode, which can be enabled in qt5-webengine with the following patch:
```Diff
diff --git a/trunk/PKGBUILD b/trunk/PKGBUILD
index 977c658..ff70366 100644
--- a/trunk/PKGBUILD
+++ b/trunk/PKGBUILD
@@ -44,7 +44,7 @@ build() {
   cd build
 
   export PATH="$srcdir/bin:$PATH"
-  qmake ../${_pkgfqn} -- \
+  qmake ../${_pkgfqn} -config debug -- \
     -proprietary-codecs \
     -system-ffmpeg \
     -webp \
```
In this mode `DCHECK*` assertions are enabled, making debugging easier. For example, the following check helps me find the actual reason to https://github.com/nextcloud/desktop/issues/941.
```
[2817:2817:1219/211037.742179:FATAL:render_process_host_impl.cc(887)] Check failed: map_.empty(). 
```

Could you consider adding this option to the qt5-webengine-debug package?

**Comment by The-Compiler** [comment]
That'd probably need to be a separate package (also see #8). For the normal `-debug` packages, I want them to be usable as a day-to-day driver, so they just should take up some more disk space, but not be any slower. With `-config debug` I'd assume more debugging stuff gets turned on, which also slows things down.

**Comment by yan12125** [comment]
Thanks for the suggestion. Yep the debug build is indeed a little bit slower. I'll create another package if I need it again :)
