### ISSUE TITLE
update.sh has problems with new qt5-quick3d package

### ISSUE THREAD

**Issue by BryceBeagle** [qutebrowser/qt-debug-pkgbuild#22]
`https://projects.archlinux.org/kde-build.git/plain/qt-opt-packages?h=qt` returns a new entry `qt5-quick3d`

Unfortunately, the [`qt5-quick3d` package](https://www.archlinux.org/packages/kde-unstable/x86_64/qt5-quick3d/) has no `trunk` directory, which means that after you try cloning the repo using svntogit, the `cp` below fails trying to find `packages/trunk`. This doesn't break anything, but you do get an (ignored) error when the script is run. `qt5-quick3d` also gets added to `pkglist` even though it actually isn't provided.

(as an aside, why not use `asp export $pkg` instead of the `git clone` approach?)

**Comment by The-Compiler** [comment]
> (as an aside, why not use `asp export $pkg` instead of the `git clone` approach?)

So that the scripts also run without any issues on non-Arch systems - the machine I build the packages on is running Debian.

**Comment by The-Compiler** [comment]
Looks like this isn't an issue anymore!
