### ISSUE TITLE
cannot install packages: "The requested URL returned error: 404"

### ISSUE THREAD

**Issue by glaubersm** [qutebrowser/qt-debug-pkgbuild#27]
error when I try to install any package from your repo

error: failed retrieving file 'qt5-webkit-debug-5.212.0alpha3-8-x86_64.pkg.tar.xz' from qutebrowser.org : The requested URL returned error: 404
warning: failed to retrieve some files

error: failed retrieving file 'qt5-translations-debug-5.14.0-1-any.pkg.tar.xz' from qutebrowser.org : The requested URL returned error: 404
warning: failed to retrieve some files

error: failed retrieving file 'qt5-networkauth-debug-5.14.0-1-x86_64.pkg.tar.xz' from qutebrowser.org : The requested URL returned error: 404
warning: failed to retrieve some files

error: failed to commit transaction (failed to retrieve some files)
Errors occurred, no packages were upgraded.

**Comment by The-Compiler** [comment]
Whoops, fixed, thanks! I forgot to move the files to the proper place after doing a manual rather than automated update this time (see #25 for details).

**Comment by glaubersm** [comment]
Thank you! :)
