### ISSUE TITLE
provides=("pkgname=version") needs to use a single "="

### ISSUE THREAD

**Issue by anntzer** [qutebrowser/qt-debug-pkgbuild#7]
... instead of two, as is currently the case (https://github.com/qutebrowser/qt-debug-pkgbuild/blob/master/qt5-base/PKGBUILD#L29).

See the `provides` section of `man PKGBUILD`.

**Comment by The-Compiler** [comment]
Hmm, you're right! Seems like I had pip's syntax in mind, which uses `==` :wink:

Do you know what effect this has in practice? I'm trying to find out whether a full rebuild is required or if that can wait until Archlinux does so upstream :wink:

**Comment by anntzer** [comment]
Yes, this makes the `provides` section useless :-)
```
$ sudo pacman -S qt5-base-debug
[sudo] password for antony: 
resolving dependencies...
looking for conflicting packages...
:: qt5-base-debug and qt5-base are in conflict. Remove qt5-base? [y/N] y
error: failed to prepare transaction (could not satisfy dependencies)
:: fcitx-qt5: removing qt5-base breaks dependency 'qt5-base=5.7.0
```

You don't need a full rebuild, `makepkg --repackage` is there for that.

BTW, you may be interested by https://bugs.archlinux.org/task/51285.

**Comment by The-Compiler** [comment]
Doing a full rebuild is still easier (as this happens inside Docker containers on a very beefy Debian server), the main pain is increasing the `pkgver` and forcing everyone to do a full redownload for such a small change, but I guess I'm going to do that :wink:

**Comment by The-Compiler** [comment]
Rebuild is now running - thanks again!
